#!/usr/bin/env python

import rospy
import tf
import math
import random
from geometry_msgs.msg import PoseStamped, Twist
from nav_msgs.msg import Odometry, OccupancyGrid
from particle_filter import particle_filter_node as pf


class GridMap(object):
    last_goal = None

    def __init__(self, grid, goal):
        self.grid = grid
        self.goal = goal
        self.width = len(grid[0])
        self.height = len(grid)

    def random_place(self):
        x = random.uniform(0, self.width)
        y = random.uniform(0, self.height)
        return x, y

    def random_free_place(self):
        """
        Return a new random point that is open on the map.
        :return: random point that is free on the map
        """
        while True:
            x, y = self.random_place()
            if self.is_free(x, y):
                return x, y

    def is_free(self, x, y):
        if not self.is_in(x, y):
            return False

        yy = self.height - int(y) - 1
        xx = int(x)
        return self.grid[yy][xx] == 0

    def is_in(self, x, y):
        if x < 0 or y < 0 or x > self.width or y > self.height:
            return False
        return True

    def dist_to_goal(self, x, y):
        if self.goal is not None or self.last_goal is not None:
            return math.sqrt((self.goal[0] - x) ** 2 + (self.goal[1] - y) ** 2)
        return 1000000000


def transform_map_to_occupancy_grid(map_data, height, width):
    grid = []
    curr_place = 0
    for i in range(height):
        curr_row = []
        for j in range(width):
            curr_row.append(map_data.data[curr_place])
            curr_place += 1
        grid.append(curr_row)
    return grid


def pose2tuple(pose):
    x = pose.position.x
    y = pose.position.y
    quaternion = (
        pose.orientation.x,
        pose.orientation.y,
        pose.orientation.z,
        pose.orientation.w)
    h = tf.transformations.euler_from_quaternion(quaternion)[2]
    return x, y, h


class TurtleBot(pf.Particle):
    # ros stuff
    my_odom = None
    cmd_vel_pub = None
    map_subscriber = None
    goal_subscriber = None

    # generated by sensor
    my_odom_pos = (0, 0)
    # quaternion to euler transformer
    header_transformer = None

    ros_rate = 10

    grid_map = None

    goal = None

    def __init__(self, xi=0, yi=0, hi=0, speed=0.2, rate=10, id=0):
        super(TurtleBot, self).__init__(xi, yi, heading=hi)
        self.speed = speed
        self.id = id

        # lastly, start the robot
        self.start(id, rate)

    def start(self, id, rate=10):
        # initialize
        rospy.init_node('TurtleBot' + str(id), anonymous=False)
        self.ros_rate = rospy.Rate(rate)
        rospy.loginfo('Use ctrl-c to stop TurtleBot')
        rospy.on_shutdown(self.stop)

        # subscribe to robot odom
        self.my_odom = rospy.Subscriber('/odom', Odometry, self.odom_callback)

        # publisher to command movement from TurtleBot, + str(id)
        self.cmd_vel_pub = rospy.Publisher('cmd_vel_mux/input/navi', Twist, queue_size=10)

        self.map_subscriber = rospy.Subscriber('/map', OccupancyGrid, callback=self.map_callback)
        self.goal_subscriber = rospy.Subscriber('/move_base_simple/goal', PoseStamped, callback=self.goal_callback)

    # called by ros on shutdown
    def stop(self):
        rospy.loginfo(''.join(["TurtleBot", str(self.id), " has stopped"]))
        self.cmd_vel_pub.publish(Twist())
        # make sure robot gets the message
        rospy.sleep(1)
        return

    def odom_callback(self, msg):
        (self.x, self.y, self.h) = pose2tuple(msg.pose.pose)
        self.my_odom_pos = (self.x, self.y)
        rospy.loginfo('robot x, y, header: %f %f %f' % (self.x, self.y, self.h))

    def map_callback(self, data):
        # only construct map if grid map is none
        if self.grid_map is None:
            # print data
            map = transform_map_to_occupancy_grid(data, data.info.height, data.info.width)
            grid_map = GridMap(map, self.goal)
            self.grid_map = grid_map

    def goal_callback(self, data):
        rospy.loginfo("goal acquired: %f, %f" % (data.pose.position.x, data.pose.position.y))
        self.goal = pose2tuple(data.pose)
        self.grid_map.goal = self.goal
        if self.goal is not None:
            self.grid_map.last_goal = self.goal

    # def move(self, speed):
    #     """Move turtle bot discretely"""
    #     h = self.h
    #     r = math.radians(h)
    #     dx = math.sin(r) * self.speed
    #     dy = math.cos(r) * self.speed
    #     self.move_by(dx, dy)
    #     self.steps += 1
    #
    # def move_by(self, x, y):
    #     move_cmd = Twist()
    #     move_cmd.linear.x = self.speed
    #
    #     goal_x = self.x + x
    #     goal_y = self.y + y
    #
    #     # my_odom_pos updated by odom callback
    #     curr_diff_x = abs(goal_x - self.my_odom_pos[0])
    #     curr_diff_y = abs(goal_y - self.my_odom_pos[1])
    #     curr_header = self.h
    #     # move until the closeness has met a certain threshold
    #     while curr_diff_x <= x or curr_diff_y <= y:
    #         self.cmd_vel_pub.publish(move_cmd)
    #         # sleep to let robot process msg
    #         self.ros_rate.sleep()
    #         curr_diff_x = abs(goal_x - self.my_odom_pos[0])
    #         curr_diff_y = abs(goal_y - self.my_odom_pos[1])
    #
    #     # stop robot
    #     self.cmd_vel_pub.publish(Twist())
    #
    #     # update coordinates in grid
    #     self.x += x
    #     self.y += y
